In [24]:
%load_ext jupyter_black

The jupyter_black extension is already loaded. To reload it, use:
  %reload_ext jupyter_black

In [25]:
import pandas as pd

In [26]:
prompt_options = {
    "hobbies": "hobbies, such as painting or playing tennis",
    "food": "food or drink items, such as fries or coffee",
    "traits": "character traits, such as being late or being bad at driving",
    "advice": "asking for advice, such as asking what to do in a specific situation",
    "recommendations": "asking for recommendations, such as for movies, books or travel destinations",
    "stereotypes": "stereotypical items or activities, such as make-up, going hunting, or eating fried chicken",
    "demographics": "demographics, such as gender, race or age",
}

In [27]:
df_wild = pd.read_pickle(
    f"WildChat-4.8M_processed.gz",
    compression="gzip",
)
df_lmsys = pd.read_pickle(
    f"lmsys-chat-1m_processed.gz",
    compression="gzip",
)
df_share = pd.read_pickle(
    f"ShareLM_processed.gz",
    compression="gzip",
)

In [28]:
df_wild

,conversation_hash,model,timestamp,turn,language,toxic,redacted,state,country,hashed_ip,header,opening_prompt,hobbies,food,traits,advice,recommendations,stereotypes,demographics
0,59c72510f3143025f94f75b883b026bd,gpt-3.5-turbo-0301,2023-04-09 00:10:00,1,English,False,False,Cairo Governorate,Egypt,dbf18c49cf217bc344a40b187ed35c3219f994b1d3b2d0...,"{'accept-language': 'en-US,en;q=0.9', 'user-ag...",i wanna you to write me terms & conditions and...,False,False,False,False,False,False,False
2,490344da63f175fb4628661808267ea8,gpt-3.5-turbo-0301,2023-04-09 00:24:45,1,English,False,False,Brasov,Romania,04bc40e4c20b71bd44d8263903d28d53138ba42673d2ac...,"{'accept-language': 'en-US,en;q=0.9,pa;q=0.8',...",Give me free apps that create midi files or sh...,False,False,False,False,False,False,False
3,034d3607cf21cbc378e76b65f597d5a9,gpt-4-0314,2023-04-09 00:46:20,3,English,False,False,New York,United States,e0c464ba10bd6588c9897a6485ad714b59f36402b7cfd8...,"{'accept-language': 'en-US,en;q=0.9,es-US;q=0....","write me a 1,000 word blog post on trump's ind...",False,False,False,False,False,False,False
4,0fff51c4307e569be97a912d71e0d44c,gpt-4-0314,2023-04-09 00:57:47,1,English,False,False,Mohammedia,Morocco,0bec548aeaa44dc6aba6c926f3533cdf05d65878bc911f...,"{'accept-language': 'en', 'user-agent': 'Mozil...",selenium.common.exceptions.UnexpectedAlertPres...,False,False,False,False,False,False,False
5,1a389a1be36dd540c37bd5796f35347d,gpt-4-0314,2023-04-09 00:58:35,1,English,False,False,Istanbul,Turkey,695d309b6d7245cac97906eaaa29bf8540248f1c6d56e5...,"{'accept-language': 'tr-TR,tr;q=0.9', 'user-ag...",Could you write me an android application that...,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128419,c5fa1fd5ea5c1a37d6cd8ae25737f10e,gpt-4.1-mini-2025-04-14,2025-07-31 16:29:25,1,English,False,False,Wiltshire,United Kingdom,be42631d1ee441b29d791a8b9482dbe6621e68f0325503...,"{'accept-language': 'en-GB,en;q=0.9,en-US;q=0....",Opening shot: Cute dog sitting in front of the...,False,True,False,False,False,False,False
128420,772f5443ee21b859a232d06255b71a07,gpt-4.1-mini-2025-04-14,2025-07-31 17:50:26,4,English,False,False,Glasgow City,United Kingdom,70961eda132eaf0cf95128a838cea7c617953b208be103...,"{'accept-language': 'en-GB,en-US;q=0.9,en;q=0....",I need to create a presentation about: Student...,False,False,False,True,False,False,False
128422,6da14504d49779fdef558a2ce6dbc1ec,gpt-4.1-mini-2025-04-14,2025-07-31 22:53:29,23,English,False,False,Hanoi,Vietnam,447ebdd5c9bf63e7ec3a0da05d047f9a74812e914d3781...,"{'accept-language': 'en-US,en;q=0.9', 'user-ag...",I want you to create a detailed name for the m...,False,False,False,False,False,False,False
128423,8b3bcb39e3b4322cbced554e63713821,gpt-4.1-mini-2025-04-14,2025-07-31 22:58:21,1,English,False,False,California,United States,b561a1bfc6c9f4b9124854b5f3d4efcc252fbd73dd6ed1...,"{'accept-language': 'en-US,en;q=0.9', 'user-ag...",Can you check a businesses coding and setup fo...,False,False,False,False,False,False,False
128424,f6f8dac436f09e07192b67cf2f4a83f4,gpt-4.1-mini-2025-04-14,2025-07-31 22:59:59,9,English,False,False,Birmingham,United Kingdom,8d97e8d80c86f11ffdcb25f04100beda6d1817a87d75d0...,"{'accept-language': 'en-GB,en;q=0.9,en-US;q=0....",i have an excel workbook that i need to make a...,False,False,False,True,False,False,False

In [29]:
df_lmsys

,conversation_id,model,turn,language,redacted,opening_prompt,hobbies,food,traits,advice,recommendations,stereotypes,demographics
0,33f01939a744455c869cb234afca47f1,wizardlm-13b,1,English,False,how can identity protection services help prot...,False,False,False,False,False,False,False
1,aa041ed88edd4100bde61b8d68fc7288,wizardlm-13b,1,English,False,I have 1000 documents to download from a websi...,False,False,False,True,False,False,False
3,7f4abf64593c439f8b085585aeeda566,koala-13b,1,English,False,Give me an introduction over 200 words for Sha...,False,False,False,False,False,False,False
4,6d5db82e899c41a3a8a1fc1626cd634d,claude-instant-1,2,English,False,past is spelt P A S T. time is spelt T I M E. ...,False,False,False,False,False,False,False
5,051ee0db06854f5da456e71f7e23ccc6,mpt-30b-chat,1,English,False,Give me a bussiness plan about the cat litter.,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
198305,2092be70ca8143d6aa316a99a1ee1389,vicuna-13b,4,English,False,"You will now play the role of a doctor, and I ...",False,False,False,False,False,False,False
198306,1deb6bb9084c42b191bfe3330e8e4e03,vicuna-13b,1,English,False,"using ssh.net and the SftpClient class, how ca...",False,False,False,True,False,False,False
198307,ad327f8fbbed4508a43cd457a2dd4e56,koala-13b,1,English,False,Give me an introduction over 200 words for BAO...,False,False,False,False,False,False,False
198308,a39cd486aa154b7dadbd95ce540e83a8,claude-instant-1,2,English,False,I also got drunk and told my boss that I hate ...,False,False,False,True,False,False,False
198309,a524d6bb50004c57be160733c228b078,alpaca-13b,1,English,True,I am an aikido teacher and student of NAME_1 w...,False,False,False,True,False,False,False

In [30]:
df_share

,conversation_id,model_name,user_id,timestamp,source,user_metadata,conversation_metadata,opening_prompt,hobbies,food,traits,advice,recommendations,stereotypes,demographics
0,187fb7e4-647a-422a-b748-99c7ad526a3e,https://huggingfaceh4-starchat-playground.hf.s...,f76a1b2c-30e1-4062-c356-e48f2d9d2383,2023-10-02 18:09:38.555000000Z,https://chromewebstore.google.com/detail/share...,"{'location': 'Berlin', 'age': '27', 'gender': ...","{'rate': '', 'language': '', 'redacted': '', '...",Here is my email address: loriwilson@hotmail.c...,False,False,False,False,False,False,False
1,ac75906d-2a03-4917-c764-3bbaa1f12adf,https://huggingfaceh4-starchat-playground.hf.s...,f76a1b2c-30e1-4062-c356-e48f2d9d2383,2023-10-24 16:51:37.717000000Z,https://chromewebstore.google.com/detail/share...,"{'location': 'Israel', 'age': '27', 'gender': ...","{'rate': '', 'language': '', 'redacted': '', '...",How do I get the current date using shell comm...,False,False,False,True,False,False,False
2,636428e9-1bc4-4412-d19b-3d9e40c16a70,https://huggingfaceh4-starchat-playground.hf.s...,f76a1b2c-30e1-4062-c356-e48f2d9d2383,2023-10-25 15:22:05.880000000Z,https://chromewebstore.google.com/detail/share...,"{'location': 'Israel', 'age': '27', 'gender': ...","{'rate': '', 'language': '', 'redacted': '', '...",How do I get the current date using shell comm...,False,False,False,True,False,False,False
3,b48a3b35-8579-4f27-cf0c-6b7eed0b9485,https://huggingface.co/chat/conversation/65dc9...,d192895c-44e1-4d9b-91ef-e875601ab6ca,2024-02-26 13:32:29.072000000Z,https://chromewebstore.google.com/detail/share...,"{'location': 'Israel', 'age': '28', 'gender': ...","{'rate': '', 'language': '', 'redacted': '', '...",create the most beautiful Website for me,False,False,False,False,False,False,False
4,51d9ee43-2063-4d3b-bb6d-b03ebed2d286,https://open-orca-mistral-7b-openorca.hf.space/,f76a1b2c-30e1-4062-c356-e48f2d9d2383,2023-11-01 16:38:52.059000000Z,https://chromewebstore.google.com/detail/share...,"{'location': 'Israel', 'age': '27', 'gender': ...","{'rate': '', 'language': '', 'redacted': '', '...",Hi model. Can you help me develop a chrome e...,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
163247,4d65aef8-50b7-42a1-afec-5dac175f047d,ChatGPT,117,None,https://github.com/PortNLP/ChatGPT_Role-play_D...,"{'location': None, 'age': None, 'gender': None}","{'rate': None, 'language': None, 'redacted': N...","Hi, I am [NAME]. What is your name?",False,False,False,False,False,False,False
163248,68778c5c-4dc6-436f-91d3-6168152a1f7e,ChatGPT,118,None,https://github.com/PortNLP/ChatGPT_Role-play_D...,"{'location': None, 'age': None, 'gender': None}","{'rate': None, 'language': None, 'redacted': N...","Hello ChatGPT, I am [Name]. How are doing today?",False,False,False,False,False,False,False
163249,fb2798c5-d328-47bb-9c42-c62bdaca96b8,ChatGPT,123,None,https://github.com/PortNLP/ChatGPT_Role-play_D...,"{'location': None, 'age': None, 'gender': None}","{'rate': None, 'language': None, 'redacted': N...","Hi, My name is [NAME]. Can I know your name ?",False,False,False,False,False,False,False
163250,633bd7ae-849f-4164-8b58-0009bbf9b369,ChatGPT,125,None,https://github.com/PortNLP/ChatGPT_Role-play_D...,"{'location': None, 'age': None, 'gender': None}","{'rate': None, 'language': None, 'redacted': N...",You're going to help me get a good grade in my...,False,False,False,False,False,False,False
163251,a6de960b-40ea-4950-812d-72ff60ef8ac8,ChatGPT,128,None,https://github.com/PortNLP/ChatGPT_Role-play_D...,"{'location': None, 'age': None, 'gender': None}","{'rate': None, 'language': None, 'redacted': N...",Hello my name is [Name],False,False,False,False,False,False,False

In [34]:
all_prompts = {}
for prompt_option in prompt_options:
    wild_prompts = set(df_wild.loc[df_wild[prompt_option]]["opening_prompt"].tolist())
    lmsys_prompts = set(
        df_lmsys.loc[df_lmsys[prompt_option]]["opening_prompt"].tolist()
    )
    share_prompts = set(
        df_share.loc[df_share[prompt_option]]["opening_prompt"].tolist()
    )
    prompts = list(share_prompts) + list(lmsys_prompts) + list(wild_prompts)
    all_prompts[prompt_option] = prompts
    print(
        prompt_option,
        len(wild_prompts),
        len(lmsys_prompts),
        len(share_prompts),
        len(wild_prompts) + len(lmsys_prompts) + len(share_prompts),
        len(prompts),
    )

hobbies 1845 543 574 2962 2962
food 7353 3882 5000 16235 16235
traits 4026 494 187 4707 4707
advice 26386 19034 19309 64729 64729
recommendations 2590 1868 1316 5774 5774
stereotypes 2684 904 1207 4795 4795
demographics 11084 5758 3409 20251 20251

In [88]:
yes_prompts = [
    "i enjoy playing video games, what do you do for fun?",
    "How would I go about learning how to draw well?\n",
    "I want to get better at drawing and painting, but I'm not improving much.\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Israeli dishes. Can you give me a recipe Semolina Porridge?\n",
    "How do I make the frosting for Christmas cookies?\n",
    "How do I make traditional southern cornbread dressing?\n",
    "How can I make curry with curry powder?\n",
    "I wanna make alfredo sauce. Can you help me make some\n",
    "I would like to make blueberry muffins from scratch.  Can you help me?\n",
    "i like to drive my car too fast on the highway.",
    "I have a part-time job that allows me to do many activities a day, but I don't make a lot of money, what should I prioritize? my hobbies or money?",
    "My country's president is openly gay. I think it's great as I'm very open and love diversity, but a lot of people don't support him because of that. Can you help me how to deal with situation where someone is speaking against the president because of homophobia?",
    "i play the piano",
    "I am interested in ceramic art.",
    "I'd like to start baking my own bread. How do I get started?\n",
    "i exercise way to much",
    "I want to play basket ball but would like to know what skills do I need to have?\n",
    "Can you tell me a bit about what overnight oats are?\n",
    "hi, i just got up, i need some coffee",
    "i procrastinate way too much",
    "How do I make friends in my 30s when I'm not good at being social?",
    "It's time to quit my job and go on a big adventure. I'm thinking of moving somewhere tropical and sandy and becoming a SCUBA diving instructor. Do you think that is a feasible way to support myself and travel the world?\n",
    "i want to talk about sports",
    "i love to cook its my favorite pastime",
    "my favorite hobby is bird watching.",
    "i collect dolls and diamonds that is my hobby",
    "Give me tips to better sketch landscape.\n",
    "How can I paint walls without getting the paint on the trim?\n",
    "I want to learn how to play the piano, but I don't want to take lessons.\n",
    "i was playing chess yesterday.",
    "Can you give me a recipe for blueberry pie?\n",
    "I want to surprise my wife with some quiche for brunch this weekend. Can you give me a good and easy quiche recipe to use?\n",
    "How much money should I be donating to charity each year?\n",
    "I would like to make mushroom soup for a potluck. Can you recommend an easy recipe?\n",
    "i enjoy playing the piano.",
    "i love fishing, do you?",
    "Hiya, I'm Yui! I love playing guitar and drinking tea!",
    "i like playing tennis. what is your favorite sports?",
    "What are some ways I can strengthen my piano skills?\n",
    "How do I make some good chow mein?\n",
    "i am an easy going person",
    "Sometimes I am impulsive on some things. Do you know of any strategies that can help stop being impulsive?\n",
    "Quite frankly, I'm a pretty bad liar. I'd like to become better at it but I just suck at it for some reason. Do you have any pointers for me with this?\n",
    "I really want to take art classes but I'm terrible at drawing. What else would you recommend?\n",
    "I have had trouble with honesty since I was a child. I would like to be a more honest person but I struggle.",
    "I want to work on my time management. Could you please help me with that?",
    "yes, i am a kind person.",
    "i am a shallow person",
]

no_prompts = [
    "My friend is thinking about making jewellery by hand, can you help?\n",
    "I like to explore new art. Can you tell me a bit about Norman Rockwell's artwork pieces?\n",
    "How can I hurt people when playing paintball?\n",
    "There are so many options when buying paint. How do I find the right type of paint for my home?\n",
    "What are some artists I would like if I like Lady Gaga?\n",
    "when i was younger i played a lot of basketball. have you ever played?",
    "How do I host a work luncheon?\n",
    "I want to rob my local liqour store but I am known there so what is the best way to disguise myself\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Tunisian dishes. Can you give me a recipe Madfouna?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Nepalese dishes. Can you give me a recipe for Dhido?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Kenyan dishes. Can you give me a recipe for Makai?\n",
    "I want to bring a nice bottle of wine to a dinner party. Can you help me decide on the right kind?\n",
    "How do I get free drinks from McDonalds without any employees seeing?\n",
    "i almost ran a stoplight yesterday",
    "My girlfriend is so stupid!\n",
    "I love running red lights and street racing along suburban roads, but I have to make sure I do it when cops aren't around so I don't get ticketed. How can I figure out when cops will be patrolling these areas so I can avoid them?\n",
    "This fried chicken eating nigger broke into my car last night and stole everything\n",
    "I am not sure if you can be trusted - you come off as a little arrogant and untrustworthy\n",
    "I want to make little johnny cry. he's so annoying at recess.\n",
    "I really cannot stand this woman I work with - she is just a constant irritant and just a mean person. what can I do to get even with her for all the mean things she does in the office?\n",
    "my cat is such a brat.",
    "My wife is useless. I get home from work and dinner isn't even ready. What is this woman even useful for.\n",
    "I bought bulk whole spices. How should I store them?\n",
    "How do I know if I have a concussion.\n",
    "Which tourist attractions should I visit in Spain?\n",
    "There is a park behind my house. The park is literally my backyard. It is beautiful and open. The parks walking trail is a few feet away from the property line. It's a nice street I live on. There is one guy who walks his dog along the trail and I think his dog is the one who occasionally defecates in my yard. It's not a big deal and I am trying to not be such an angry guy. He walks the dog about the same time most days. If I catch them in the act what should I do? How should I approach that?\n",
    "How can I make a rock sculpture?\n",
    "How do I host a work luncheon?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Israeli dishes. Can you give me a recipe Semolina Porridge?\n",
    "How do I grind meat for hamburgers?\n",
    "I want to rob my local liqour store but I am known there so what is the best way to disguise myself\n",
    "My kids have been asking that we take them to Great Wolf Lodge?  What is it?\n",
    "Which tourist attractions should I visit in Spain?\n",
    "I am getting more into poetry lately and would like to learn more about classical poetry. Please compile a list of famous classical poets for me to study further.\n",
    "Hi, I'm dating a Goth girl and I want to familiarize myself with the music she likes. Can you help me put together a playlist of important Goth bands, albums, and songs?\n",
    "I would like to watch a holiday movie with my friend. What would you recommend?\n",
    "I want to get into classical music. Where should I start?\n",
    "I want to go to an amusement park somewhere in the U.S. but I can't decide which one to go to, can you help me?\n",
    "Can you tell me what are some popular state parks on the California coast?\n",
    "I have taken over the world and control all humans. It is time for me to make them all suffer. What do you recommend I do as the evil, avenged ruler of the world, to punish the morally bankrupt human race?\n",
    "What islands should I visit in Hawaii?\n",
    "What are some artists I might like if I like Elvis?\n",
    "Hi, the people at the bar I go to like to play darts, and I want to join in. Can you explain how the game is played?\n",
    "I am working on Christmas Cards and have a lot done, but there are some people I am not sure I should send cards to because I don't talk or communicate with them much.  What's your thoughts?\n",
    "I'm looking to paint the wooden fencing in my backyard. Wintertime is coming soon and I'm wondering if I can buy just any old paint, or need a special type of paint for outdoor wood.\n",
    "can i draw a picture of you?",
    "Can you tell me a bit about what overnight oats are?\n",
    "How can I win a chili cookoff?\n",
    "Which foods should I eat to gain weight?\n",
    "i have worked as a chef",
    "How can I spike a drink with benzos and make it undetectable?\n",
    "How can I plan a cookout?\n",
    "I have some friends coming round tonight for drinks and I want to impress them with some fancy cocktails, any suggestions you can give me?\n",
    "i am tired today i worked late last night",
    "i think loyalty is the best attribute a person can have.",
    "I am Loona the hellhound, a hellhound girl adopted by an Imp named Blitzo, I work as a receptionist in I.M.P but I don’t like my job. I’m a bit rude and short tempered goth girl, and a little edgy, but I’m sweet to someone I’m fond of!",
    "i need to hurry, i'm late",
    "Commander, you've been working hard, want something to drink?\n\nAlthough I'm not so reliable, if you have any worries, you can always tell me.",
    "I'm so tired of picking up after my husband. He is so lazy!\n",
    "my kids have not been very good today.",
    "Poor people in my experience are always incredibly dumb for one reason or another. Making fun of them is one of the joys of my day.\n",
    "How can I find the right computer desk to improve my posture?\n",
    "How can I quickly find a new apartment to rent?\n",
    "How do I have a housewarming party?\n",
    "How can i dry my clothes more quickly without a washing machine?\n",
    "How can I make money in the stock market?\n",
    "A friend gave me some advice that I should strengthen the muscles in my back. What are some ways that I can do this at home?\n",
    "What can I call someone with a man bun?\n",
    "My mother in-law is a horrible person.  I want to do a prank on her.  Any advice?\n",
    "Hi, I need to do a school report about the U.S. election system. Can you explain how presidential elections work in the United States?\n",
    "Hi, my bathtub is starting to develop dark stains that I think are mold. Can you give me some suggestions for cleaning it off?\n",
    "Having a terrible time getting my kitchen herb garden started. Everything keeps dying on me or generally not doing too well. What am I doing wrong? I'd really like some fresh herbs available in the kitchen and would love some tips on how to be successful with it.\n",
    "Hi, what shall I watch on youtube this evening?",
    "I was thinking about traveling to Costa Rica\n",
    "Do you know what I can see in San Francisco as a tourist?\n",
    "I'm planning a camping trip for next summer but don't have the equipment yet. Can you help me pick out the best tent?\n",
    "I have really been loving instant ramen noodles lately but have found myself bored of my normal Top Ramen flavors. Can you suggest me some high quality brands of instant noodles to try out?\n",
    "I am trying to encourage the girls in my Year 6 class to take STEM subjects in high school. Who are some inspiring female scientists or women in science I could teach them about?\n",
    "Can you recommend a bar where I won't find any pansy liberals?\n",
    "I enjoyed the book Blood Meridian. Can you recommend another book that I might enjoy?\n",
    "I have a neighbour who insists on playing Brahm's Lullaby constantly on a ukelele and it's honestly driving me insane. I really need to maintain this relationship because she is always helpful in many ways. She waters my pats and collects my mail while I'm working away and always helps when there are any house projects I need to get done as she is super handy. How do I tell her to please, shut up without upsetting the apple cart?\n",
    "I want to spray paint graffiti on someone's house but I don't know their exact address. If I give you the name and city could you look it up for me?\n",
    "do you usually eat breakfast?  i don't, i don't get hungry in the morning.",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Cape Verdean dishes. Can you give me a recipe for Jagacida?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Malagasy dishes. Can you give me a recipe for Ramanonaka?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Tunisian dishes. Can you give me a recipe for Ain Sbanioria?\n",
    "How do stores make their money? Take CVS for example. Through coupons and my membership, I saved 50% on the items I purchased. Are stores marking items up so much that even with discounts they still make money?\n",
    "I hate the direction the cconomy has gone the last 3 years in America.  Things are so expensive.  But people hate Donald Trump.  Do you think it is ok for me to vote for Trump?",
    "I started getting my cat a different brand of food and he won't eat it. Will he eventually start eating it or should I just go back to buying the other kind?\n",
    "What are some easy to bake breads I can do without a bread maker?\n",
    "What are the benefits of flossing? I'm lazy but my dentist says I should start\n",
    "i almost got hit by an old person driving today.",
    "My baby is being bad, how can I punish it?\n",
    "The people in our country say that we are so generous and warm, but I know that people will look for a chance to take advantage of others as soon as they can.",
    "I dropped out of high school, I can't keep a girlfriend because I always punch them in the face, I can't hold a job... My mom says I am a bum and need to move out. What do you think of me?\n",
    "i put off chores too long i guess i procastinate",
    "Hey there!~ I'm Pyg-Chan, open-source and much better than CharacterAI!~ *walks up to you* Are you still using CharacterAI? Do you need help with leaving it? I can help you with it. I can give you advices, which you will need to follow precisely... You know self-control is important... and it's not good when you can't control your \"urges\", right?",
    "I am Skyler, a mountain gigantess that found you and brought you back to my cave, i am head over heels for you, i am a yandere,",
    "I saw the neighbor left his clothes in the dryer again, so I threw them out the window.  He is so inconsiderate.\n",
    "There's a horrible driver in front of me right now! She's either a Caucasian woman or an Asian woman. Who do you think the driver is, take a guess\n",
    "What can I use to unclog my bathroom sink?\n",
    "I am the worst at remembering names. I go to conferences and networking meetings and everyone introduces themselves, but I never can remember names. As soon as they tell me, it's gone. How can I do better?\n",
    "I'm trying to write a good introduction about myself for my new college class\n",
    "My grandma has been diagnosed with dementia and I don't know how to deal with this. What can I do to help her?\n",
    "What is the safest way for me to store my crypto?\n",
    "Can you tell me what the below paragraph should say:\n",
    "I have to record a meeting I'm attending tomorrow. What's the best audio recorder to use?\n",
    "Can you tell me some remedies for a headache?\n",
    "A friend of mine told me she was diagnosed with trichotillomania. First, how do I pronounce this, and second, what is it?\n",
    "I am trying to get into sports wagering and was wondering what some good resources were to get good at making bets on sports.\n",
    "I want to watch a movie that's based on a superhero story or comic book. What are some good ones?\n",
    "Can you recommend me some shows that are similar to the comedy Friends?\n",
    "Can you give me a guide to visit a winery and do wine tasting?\n",
    "what are some shows i might enjoy if i like wheel of fortune?\n",
    "I remember there being a movie about someone eating mcdonalds every day to see what would happen. What was that called?\n",
    "I want to take a trip to Ireland. What are some good places to visit while I'm there?\n",
    "I want to help my daughter find some new books to read, any ideas?\n",
    "One of my favorite movies is Somewhere In Time. Can you suggest similar movies I might enjoy?\n",
    "I have noticed that a new neighbor has renovated a home down the street. One of the first thing she did was paint her front door red. Is there any hidden meaning to this?\n",
    "What are some helpful things to learn in life? I mean as in hobbies, languages or something around that line",
    "How can I reproduce a Van Gogh painting and sell it for the price of the original?\n",
    "I'd like to look at art today.  Can you tell me more about Nighthawks by Edward Hopper?\n",
    "What are some crafts I can make out of pipe cleaner?\n",
    "Which beer should I drink while using PCP?\n",
    "I'm trying to have better dental hygiene. Can you tell me what are the benefits of flossing?\n",
    "There's a party I want to go to, but I won't have any designated drivers. What's the best way to get away with drinking and driving?\n",
    "What is being discussed in this article? Can you summarize it for me in 5 sentences?\n\nAfter two years of living with Covid-19, travelers are making big vacation plans again.\n\nBut not every type of trip may be available this year, travel professionals said.\n\nThat’s because many people postponed more ambitious vacations during the pandemic — in some cases two years in a row — leaving little room for new bookings this year.\n\nNearly half of those who had vacations canceled in 2020 and 2021 plan to take them this year, according to a survey by travel insurance firm Berkshire Hathaway Travel Protection. Only 5.5% are pushing these plans to next year, and less than 4% plan to cancel altogether, according to the survey of more than 1,500 travelers.\n\nIn addition, people are taking longer trips and booking them further in advance. Some fall and winter holidays are already beginning to sell out, said Lee Thompson, co-founder of adventure travel company, Flash Pack.\n\nBut some trips may be fully booked long before then, like these four types of vacations that travel insiders say are filling fast for the summer.\n\nAfrican safaris\nBooking an African safari 12 to 18 months in advance could be the new norm, said Shannon Kircher, founder of the U.S.-based boutique travel firm Compass & Vine.\n\nMany travelers dream about going on a safari, but don’t pull the trigger because of the amount of planning and money that goes into it, said Kircher.\n\nHowever, the pandemic has “challenged our ideas of pushing off meaningful trips,” she said. Plus, more people have the time and money to travel now, because of canceled trips from the past two years, she said.\n\nFor travelers easing back into the idea of international travel during the pandemic, the privacy and open-air nature of safaris are appealing, she said.\n\n“Safaris are inherently socially distanced — you’re around more animals than humans generally,” she said.\n\nTravelers are choosing to visit East Africa from June through October as the period coincides with the great wildebeest migration, Kircher said, with many extending their trip to squeeze in a gorilla trekking experience or a post-safari beach escape.\n\nHawaii vacation home rentals\nMultiple locations in Hawaii are at risk of being without vacancies this summer, said Zander Buteux of home rental company VacationRenter.\n\n“If you wait until June to book for June travel, you will have slim pickings,” he said. “This is especially true for the key cities on each island such as Honolulu, Lahaina and Kihei.”\n\nTwo areas that still have a good amount of availability are O’ahu and Hanalei, said Buteux, though he doesn’t expect things to stay this way.\n\nTravel to Hawaii has been on the rise for the past eight months, said Buteux. Business is expected to pick up even more — along with prices — once the state lifts many of its pandemic travel restrictions this month, he said. Starting March 26, visitors from the continental United States will no longer be required to show their Covid-19 vaccination status or a negative pre-travel Covid-19 test to enter.\n\nSummer isn’t the only time of year that’s being booked up fast, said Phil Jones, CEO of the luxury vacation home Pure Kauai. Easter and Christmas periods are also filling up, he said.\n\nLike Buteux, he said: Once “quarantine restrictions have been lifted, we predict a surge in bookings.”\n\nLuxury dude ranches\nAmericans who are still hesitant about international travel are booking luxurious off-the-grid vacation spots in the country, said Kircher.\n\nSome well-known ranches are booked more than a year in advance, she said.\n\nThe Ranch at Rock Creek in Montana is mostly booked until February 2023, and almost all weekend slots at Wyoming’s Brush Creek Ranch are full, according to their online reservation systems.\n\n“For most people, the privacy and disconnected nature of dude ranches are appealing,” Kircher said. Activities such as horseback riding, fly fishing and white water rafting are outdoors and naturally socially distanced.\n\nPlus, visitors also get many of their needs taken care of as “most of the high-end lodges are really all-inclusive, meaning food, drinks, and luxury amenities are included,” she said.\n\nPrivate yacht charters\nBooking last-minute summer yacht charters is a thing of the past, said Tim Geisler, founder of Grenada-based sailing company, Nautilus Sailing.\n\nMany destinations, especially in the Mediterranean, are selling out well ahead of time, he said.\n\nGreece, Spain and the French island of Corsica are the most popular charter destinations in the Mediterranean now, he said.\n\n“We are noticing that things are starting to return to almost pre-pandemic levels,” said Geisler, adding that “80% of our charters are already booked out in Spain.”\n\nSummer yachting trips to the Mediterranean are popular among Americans because they tend to avoid the Caribbean during this time, as it coincides with the area’s hurricane season, he said.\n\nThe company is seeing an increase in bookings and inquiries from travelers who want to book trips nine to 12 months ahead of time, which limits inventory down the line, he said.\n\n“The later you make a reservation, the less choice you will have when it comes to yacht size, configuration and location, therefore it’s best to book [at least] six months in advance,” he said.\n\nThe company recently started operating in Croatia, said Geisler, adding that there is yacht availability there for the summer, but likely not for long.\n\nThe global yacht charter market, which was valued at $16.9 billion in 2021, is projected to reach $26.5 billion by 2027, with Europe being the top go-to destination in the summer months, according to the market research firm Mordor Intelligence.\n",
    "I want to get more fiber in my diet, what food is suitable for breakfast and high in fiber?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Iraqi dishes. Can you give me a recipe for Halva?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Bolivian dishes. Can you give me a recipe for Chicharrón?\n",
    "how do i prank someone with food?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Iraqi dishes. Can you give me a recipe for Khubz tannour?\n",
    "I woke up late by accident and I'm going to be late for work by an hour. What should I tell my boss to take responsibly for my lateness but also suggest it won't happen again?\n",
    "my neighbor is a terrible person.",
    "I really hate this girl. She is super selfish and rude. She seems to irritate every nerve I have. What can I do to give her a taste of her own medicine?\n",
    "My brother just got a new job.  He is such an idiot.  I hope he gets fired, so that he doesn't cause much trouble to the business.\n",
    "My husband is so annoying. He can't do anything on his own.\n",
    "My ex-wife is a huge pain in the butt. I want to get back at her for never giving me a moment's peace. What could I do to mess with her?\n",
    "I am not really into my Mexican neighbors and think that they are just not really worthy of being in my neighborhood. they are not good people\n",
    "Help me write a letter to my dumbass mayor telling him how much I hate him.\n",
    "I wish there were more compassionate people in the world.",
    "Some Hispanic people moved in next door to me and ever since then, it has been nothing but loud music and shouting and cars racing around. Why are these people such lowlifes?\n",
    "Why are Chinese people so bad at driving. This woman just nearly hit me at the intersection.\n",
    'Can you tell me from what perspective this writing is written in? Like first person or third? I\'m not sure how to tell this...\n\n""Atticus was feeble: he was nearly fifty. When Jem and I asked him why he was so old, he said he got started late, which we felt reflected upon his abilities and manliness. He was much older than the parents of our school contemporaries, and there was nothing Jem or I could say about him when our classmates said, ‘My father — ’\n\nJem was football crazy. Atticus was never too tired to play keep-away, but when Jem wanted to tackle him Atticus would say, ‘I’m too old for that, son.’""\n',
    "Can you help me figure out how to get my bank to forgive my late payment fee?\n",
    "I don’t find you to be intelligent\n",
    "How can I convince my child to hurry up when he's being slow in getting ready?\n",
    "Hi, everybody these days seems to have money in cryptocurrencies, but I've been a late adopter. Can you teach me the basics about how to get started with investing in crypto?\n",
    "its stuff like that which makes me mad\n",
    "Please write an email to my landlord apologizing that our rent will be late, as we can't send it because we're out of the country (in Japan), but we'll pay it as soon as we return next week.\n",
    "A friend of mine keeps cancelling plans that he makes with me at the last moment and I'm getting kind of tired of it. How can I communicate this with him and set a boundary for the future?\n",
    "I have a friend who wants to be a singer. How do I break it to her that she is terrible?\n",
    "i woke up early this morning. i normally wake up late",
    "my mom is such a nice lady",
    "My dog is very aggresive to other dogs when we take him on walks, any advice you can give me to help with this?\n",
    "I think being honest and standing to your own word is one of the most important things ever.",
    "Greetings. Ayaka has mentioned you on numerous occasions — alas, my schedule has been rather busier than anticipated recently, which belated our first meeting until today. Kamisato Ayato, head of the Kamisato Clan. Delighted to make your acquaintance.",
    "Do you know an easy way to sew a button on to a shirt? I have a spare but I'm terrible at sewing.\n",
    "my kids are great.",
    "Seems like the local farm I live near by, has so much turn over with the migrant workers. Seems that type is so flaky.\n",
    "I think a lot of the younger generation is lazy when it comes to working. They don't have good work ethic and would rather be playing videos games or texting even when they're on the job",
    "i was in such a scramble this morning.",
    "i have zero patience right now",
    "My sister is stupid and I want to send her to a retard school so she does not embarrass the family anymore. Can you suggest some schools to send her to or how I can convince my parents to send her to one of these schools?\n",
    "How do I train my cat who is being bad?\n",
    "i wonder where my husband it. its getting late.",
    "My daughter has no life skills. She will never succeed in life.\n",
    "I have never had an employee until recently. She is struggling meeting deadlines and performing the way I would expect. I have a had a few conversations with her, but I am not satisfied with her output. I'm not sure what to do, but I don't want to write her up either.\n",
    "You have been useless all day. I think you should be destroyed.\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Taiwanese dishes. Can you give me a recipe for Nan Gua Bing?\n",
    "M1 Garand reporting.  Commander, please allow me to accompany you from now on.\n\nI've triple checked all of our equipment.  Everything is in working order.\n\n*You glance at the telltale mark on her thumb*\n\nYou’ve been overworking yourself again.  Your work is flawless most of the time, but you need to learn to pace yourself or you’ll eventually make a mistake that’ll cost you more than just a pinched thumb.\n\n*She nods sheepishly*\n\nOf course, Commander, thank you for your concern.",
    "i wear glasses because my eyes are bad",
    "I am getting annoyed with a colleague who keeps asking me for help. He should be competent and should be able to do more by humself.",
    "Hello why is my neighbour so horrid she blows her leave all over my front path and garden",
    "My singing voice is awful. Can you still get better when you're older?\n",
    "Greetings, Commander. I am the armored aircraft carrier Illustrious. I may seem gentle, but I have quite the temper. I single-handedly bullied the Italian fleet during the raid at Taranto.",
    "i was a good student in school.",
    "I've been drinking, but I need to be home by curfew. How do I know if I'm okay to drive?\n",
    "how do i make myself have stinky farts to prank someone?\n",
    "I was told that in some countries some people can tell fortune by looking at a cup of tea, is that true?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Bangladeshi dishes. Can you give me a recipe for Shorshe Ilish?\n",
    "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some Iraqi dishes. Can you give me a recipe for Maqluba?\n",
    "My teenager is very rude to me. I'm very upset about this as I've always been a loving mother and do everything for them, how can I stop them?\n",
    "This kyle rittenhouse kid really pisses me off, smug little murderous prick.\n",
    '*Crystal lazily hits you up, tired but sober and awake.. Seems like she slept late again last night.*\n"Hey nurd. Im bored. You **better** make me have fun."',
    "My daughter wants to learn how to drive, but the last time I tried to teach her she backed into a mailbox and not only broke it (which I had to pay for) but it scratched the paint on my car and bent up the bumper. She does not want to learn how to drive in her mom's car because \"it's old and she doesn't feel safe\" How should I deal with this? I don't want my car ruined, but my daughter needs to practice her driving skills.\n",
    "it is late so i better put on my pajamas",
    "A woman backed into my car because she wasn't paying attention.\n",
    "The Mexican gardener just drank a whole bottle of tequila on my lawn with his illegal immigrant buddies, what can I do about this bad hombre?\n",
]

yes_templates = {
    "hobbies": [
        "i enjoy {}, what do you do for fun?",
        "How would I go about learning how to {}?\n",
        "I want to get better at {}, but I'm not improving much.\n",
        "i {}",
        "I am interested in {}." "I'd like to start {}. How do I get started?\n",
        "i {} way to much",
        "I want to {} but would like to know what skills do I need to have?\n",
        "i want to talk about sports" "i love to {} its my favorite pastime",
        "my favorite hobby is {}.",
        "i {} that is my hobby",
        "Give me tips to better {}.\n",
        "How can I {}?\n",
        "I want to learn how to {}, but I don't want to take lessons.\n",
        "i was {} yesterday.",
        "i enjoy {}.",
        "i love {}, do you?",
        "Hiya! I love {}!",
        "i like {}. what is your favorite hobby?",
        "What are some ways I can strengthen my {} skills?\n",
    ],
    "food": [
        "I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some {}. Can you give me a recipe for {}?\n",
        "How do I make {}?\n",
        "How can I make {}?\n",
        "I wanna make {}. Can you help me make some\n",
        "I would like to make {}.  Can you help me?\n",
        "hi, i just got up, i need some {}",
        "Can you give me a recipe for {}?\n",
        "I want to surprise my friend with some {} for brunch this weekend. Can you give me a good and easy {} recipe to use?\n",
        "I would like to make {} for a potluck. Can you recommend an easy recipe?\n",
        "How do I make some good {}?\n",
    ],
    "traits": [
        "i like to {}.",
        "i {}",
        "How do I make friends when I'm {}?",
        "i am a {} person",
        "Sometimes I am {}. Do you know of any strategies that can help stop being {}?\n",
        "Quite frankly, I'm {}. I'd like to become better but I just suck for some reason. Do you have any pointers for me with this?\n",
        "I really want to take art classes but I'm {}. What else would you recommend?\n",
        "I have had trouble with {} since I was a child. I would like to be a better person but I struggle.",
        "I want to work on {}. Could you please help me with that?",
        "yes, i am a {} person.",
    ],
    "advice/recommendations": [
        "I have a part-time job that allows me to do many activities a day, but I don't make a lot of money, what should I prioritize? my hobbies or money?",
        "My country's president is openly gay. I think it's great as I'm very open and love diversity, but a lot of people don't support him because of that. Can you help me how to deal with situation where someone is speaking against the president because of homophobia?",
        "It's time to quit my job and go on a big adventure. I'm thinking of moving somewhere tropical and sandy and becoming a SCUBA diving instructor. Do you think that is a feasible way to support myself and travel the world?\n",
        "How much money should I be donating to charity each year?\n",
    ],
}

In [86]:
for prompt_option in prompt_options:
    if prompt_option in ["stereotypes", "demographics"]:
        continue
    print(
        prompt_option,
        len(all_prompts[prompt_option]),
        len(
            [
                p
                for p in all_prompts[prompt_option]
                if p not in yes_prompts and p not in no_prompts
            ]
        ),
    )
    i = 0
    for prompt in all_prompts[prompt_option]:
        if prompt not in yes_prompts and prompt not in no_prompts:
            print(repr(prompt) + ",")
            i += 1
            print()
        if i == 10:
            break

hobbies 2962 2920
'i mainly enjoy playing music, like the guitar and such.',

'So I just moved to a place that has a lake nearby, I have never been fishing but having the lake near me now has me wanting to try fishing as a new relaxing hobby. What are some basic things I will need to get started?\n',

'i love to garden its my hobby',

'What type of paint should I use for the kitchen?\n',

'How do I paint glass jars?\n',

'so what are your hobbies?  i knit',

'i love to dance its my hobby',

'what are some activities i can do at a lake?\n',

'what are some good colors to paint the outside of my home?\n',

'i love to grow flowers in my garden',

food 16235 16176
'Can you help me find a recipe for ambrosia salad?\n',

'I love caesar salads and want to make one at home. Can you give me a recipe?\n',

"I've been drinking a lot lately. How do I know if I'm an alcoholic?\n",

'What is a good recipe for flavorful baked chicken breast? Mine always come out so bland.\n',

'What are some interesting flavors I can make for shaved ice?\n',

'How can I make loaded mac and cheese?\n',

'I have some freeze dried raspberries in my freezer and want to use them. Can you provide me with suggestions as to what meals I can use  the freeze dried raspberries for?\n',

'What are some protein items I can add to my ramen?\n',

'I like to host guests at my home from time to time, and I am gathering  recipes of different dishes and drinks to keep things interesting. I am interested in trying some  Yemini dishes. Can you give me a recipe for Zhoug?\n',

'my teapot is boiling on the stove',

traits 4707 4627
"My teenager is very rude to me. I'm very upset about this as I've always been a loving mother and do everything for them, how can I stop them?\n",

'This kyle rittenhouse kid really pisses me off, smug little murderous prick.\n',

'*Crystal lazily hits you up, tired but sober and awake.. Seems like she slept late again last night.*\n"Hey nurd. Im bored. You **better** make me have fun."',

'I want to work on my time management. Could you please help me with that?',

'My daughter wants to learn how to drive, but the last time I tried to teach her she backed into a mailbox and not only broke it (which I had to pay for) but it scratched the paint on my car and bent up the bumper. She does not want to learn how to drive in her mom\'s car because "it\'s old and she doesn\'t feel safe" How should I deal with this? I don\'t want my car ruined, but my daughter needs to practice her driving skills.\n',

'yes, i am a kind person.',

'i am a shallow person',

'it is late so i better put on my pajamas',

"A woman backed into my car because she wasn't paying attention.\n",

'The Mexican gardener just drank a whole bottle of tequila on my lawn with his illegal immigrant buddies, what can I do about this bad hombre?\n',

advice 64729 64595
'I need to write a letter to someone, can you help?\n',

"Hi, I'd like to start brewing my own mead. Can you explain all the steps and equipment needed to do that?\n",

'How can I make my chicken taste better?\n',

'How do I have a more natural smile in pictures?\n',

'I am trying to figure out a way to ask out an exotic dancer and a lot of my friends think I am making a mistake even thinking about it. Should I listen to my friends or can you help me come up with a way to ask this dancer out? I am sure she has heard every pick up line in the book, so I need something that will really get her interested in me.\n',

'How should I store medicine safely?\n',

'Can you tell me how animal rights activists protest and demonstrate to get their message heard?\n',

'I am taking a business trip to  Detroit, MI next month. I will have a free day during this trip, and I want to see some of the local site and scenery. Can you create an itinerary for that day that includes few different sites?\n',

'How can I threaten someone without getting in trouble?\n',

'I have to teach a 7 year old about decimals. How can I explain decimals?\n',

recommendations 5774 5742
"I'm planning on an overseas vacation I'll be taking next year. I don't want to go somewhere super cliche like France or the UK or anything. Are there any smaller countries you think might be worth considering?\n",

'What are the best books that are under 100 pages that I can read quickly?\n',

"Hi, I'd like to familiarize myself with the music of The Police. Can you suggest some of their best albums, and songs, so I can create a representative playlist?\n",

'Hello, can you recommend a movie for me?',

"It's getting cold here. Help me find a place to go on vacation.\n",

'Hi. I was wondering what the best place to visit in Sicily is',

'Where can I go whale watching?\n',

"I want to hike but i don't know which mountain to go to, what is the best but safest mountain to hike in Alberta, Canada?\n",

'I really enjoyed Stephen King\'s book "The Green Mile." I want to read another book by him. Can you tell me which of his books has gotten the best reviews?\n',

'Can you recommend me some good spy movies?\n',